spring.application.name=labourmanagement

spring.datasource.url=jdbc:mysql://localhost:3306/labourmanagement
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

## -----------------------------
## Enable FULL LOGGING
## -----------------------------
#
## Enable DEBUG logs for Spring Boot
#logging.level.root=DEBUG
#
## Tomcat request logging
#logging.level.org.apache.coyote.http11=DEBUG
#
## Spring Web logs (controller, request/response info)
#logging.level.org.springframework.web=DEBUG
#
## Hibernate SQL logs
#logging.level.org.hibernate.SQL=DEBUG
#
## Hibernate Parameter logs (values passed in queries)
#logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
#
## Hibernate transaction logs
#logging.level.org.hibernate.transaction=DEBUG
#
## DataSource logs
#logging.level.org.springframework.jdbc.core=DEBUG
#
## MyBatis / JDBC logs if needed
#logging.level.org.springframework.jdbc=DEBUG
#
## Show EntityManager logs
#logging.level.org.springframework.orm.jpa=DEBUG
#
#debug=true
